version: 1.0.{build}

environment:
  dropbox_email:
    secure: H0MR0m0qFb2BpJVdoaPp1Z0FWKodZSDI9dbwRc//WOQ=
  dropbox_token: 
    secure: EyZJuSKYaos2H9IjKnDq5ib00oP8hG0nnhkoBxdc9w4=
  dropbox_secret:
    secure: FLWxzSEPlCqGbBKOAB0+Fg==

build:
  project: src\Build.proj

artifacts:
  - path: artifacts\*.*

on_success:
  - ps: Start-FileDownload "https://github.com/illallangi-ps/CloudStorage/releases/download/v1.0.41/Illallangi.Enterprises.Cloud.Storage.PowerShell.Module.x64.v1.0.41.msi" -FileName "$($env:temp)\Illallangi.Enterprises.Cloud.Storage.PowerShell.Module.x64.v1.0.41.msi"
  - ps: Start-Process -FilePath "$($env:SystemRoot)\System32\msiexec.exe" -ArgumentList "/i ""$($env:temp)\Illallangi.Enterprises.Cloud.Storage.PowerShell.Module.x64.v1.0.41.msi"" /qn" -Wait
  - ps: Import-Module Illallangi.CloudStorage
  - ps: Get-ChildItem -Path "$($env:APPVEYOR_BUILD_FOLDER)\artifacts" | Push-FileToDropBox -Destination "Artifacts/$($env:APPVEYOR_REPO_NAME)" -AccessToken "$($env:dropbox_token)" -AccessSecret "$($env:dropbox_secret)"