//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Illallangi Enterprises DropBoxStartMenu")]
[assembly: System.Reflection.AssemblyCompany("Illallangi Enterprises")]
[assembly: System.Reflection.AssemblyProduct("Illallangi Enterprises DropBoxStartMenu")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Illallangi Enterprises 2014")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyInformationalVersion("Debug Build")]
[assembly: System.Runtime.InteropServices.Guid("5bd68165-52d5-4190-9640-fc2d4e197956")]
[assembly: System.Reflection.AssemblyVersion("0.0.1")]
[assembly: System.Reflection.AssemblyFileVersion("0.0.1")]


