//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.32559
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("DropBox Start Menu Linker")]
[assembly: AssemblyCompany("Illallangi Enterprises")]
[assembly: AssemblyProduct("DropBox Start Menu Linker")]
[assembly: AssemblyCopyright("Copyright © Illallangi Enterprises 2013")]
[assembly: ComVisible(false)]
[assembly: AssemblyInformationalVersion("Debug Build")]
[assembly: Guid("5bd68165-52d5-4190-9640-fc2d4e197956")]
[assembly: AssemblyVersion("0.0.0.1")]
[assembly: AssemblyFileVersion("0.0.0.1")]


[assembly: log4net.Config.Repository("Illallangi.DropBox.StartMenu")]
[assembly: log4net.Config.XmlConfigurator]